dist: focal  # ubuntu 20.04

before_install:
  - sudo apt-get -y install sagemath

install: skip

script:
  - sage --version
  - sage -python --version
  - echo $PATH
  - sage setup.py test
  - sage -pip install --upgrade --no-index -v --user .
