dist: focal  # ubuntu 20.04

before_install:
  - sudo apt-get -y install libgsl-dev liblinbox-dev libsingular4-dev libntl-dev libflint-dev libmpfr-dev libpari-dev python3-ipywidgets sagemath

install: skip

script:
  - sage --version
  - sage -python --version
  - echo $PATH
  - sage setup.py test
  - sage -python -m pip install --upgrade --no-index -v --user .
