dist: bionic  # ubuntu 18.04

language: python

env:
  global: APP_DIR=/app
  matrix:
    - DOCKER_SAGE=sagemath/sagemath:8.8
    - DOCKER_SAGE=sagemath/sagemath:latest

services:
  - docker

before_install:
  - docker pull $DOCKER_SAGE

install: skip

script:
  - docker run -v "$(pwd)":$APP_DIR -e APP_DIR --entrypoint=/bin/bash $DOCKER_SAGE $APP_DIR/.travis-test.sh
